Question.create(level: 0, text: '2 + 2 = ...', answer1: '4', answer2: '5', answer3: "I dont't know", answer4: '-1')
Question.create(level: 1, text: 'Which Disney character famously leaves a glass slipper behind at a royal ball?', answer1: 'Cinderella', answer2: 'Pocahontas', answer3: 'Sleeping Beauty', answer4: 'Elsa')
Question.create(level: 2, text: 'What name is given to the revolving belt machinery in an airport that delivers checked luggage from the plane to baggage reclaim?', answer1: 'Carousel', answer2: 'Concourse', answer3: 'Terminal', answer4: 'Hangar')
Question.create(level: 3, text: 'Which of these brands was chiefly associated with the manufacture of household locks?', answer1: 'Chubb', answer2: 'Ronseal', answer3: 'Flymo', answer4: 'Phillips')
Question.create(level: 4, text: 'Which toys have been marketed with the phrase “robots in disguise?', answer1: 'Transformers', answer2: 'Hatchimals', answer3: 'Sylvanian Families', answer4: 'Bratz Dolls')
Question.create(level: 5, text: 'What does the word loquacious mean', answer1: 'Chatty', answer2: 'Angry', answer3: 'Beautiful', answer4: 'Shy')
Question.create(level: 6, text: 'Obstetrics is a branch of medicine particularly concerned with what', answer1: 'Childbirth', answer2: 'Broken bones', answer3: 'Heart conditions', answer4: 'Old age')
Question.create(level: 7, text: 'What are made and repaired by a cobbler', answer1: 'Shoes', answer2: 'Jewelery', answer3: 'Windows', answer4: 'Glass')
Question.create(level: 8, text: 'What is the smallest country in the world?', answer1: ' Vatican City', answer2: 'Iceland', answer3: 'Spain', answer4: 'France')
Question.create(level: 9, text: 'Which airport is the opening scene of Love Actually set in', answer1: 'Heathrow', answer2: 'Luton', answer3: 'Stansted', answer4: 'Gatwick')
Question.create(level: 10, text: 'What colour were the Pyramids of Giza originally', answer1: 'White', answer2: 'Blue', answer3: 'Red', answer4: 'Orange')
Question.create(level: 11, text: 'Duroc, Berkshire and Mangalica are breeds of which farmyard animal', answer1: 'Pig', answer2: 'Cow', answer3: 'Chicken', answer4: 'Horse')
Question.create(level: 12, text: 'How many million miles away is the sun from the Earth?', answer1: '93 million', answer2: '12 million', answer3: '136 million', answer4: '200 million')
Question.create(level: 13, text: 'What was the only painting sold by Vincent van Gogh during his lifetime?', answer1: 'The Red Vineyard', answer2: 'Sunflowers', answer3: 'The Yellow House', answer4: 'The Starry Night')
Question.create(level: 14, text: 'Who won the first ever football World Cup?', answer1: 'Uruguay', answer2: 'Brazil', answer3: 'Portugal', answer4: 'Sweden')
